@startuml Ejecución
    start
        :Recibir CI del funcionario;
        
        if (CI registrada en el sistema) then (SI)
            :Búsqueda de las firmas realizadas \n**en el día**;
            :Búsqueda de última firma\n**del funcionario**\n entre las **firmas del día**;
            if (Hay Última Firma) then (NO)
                :Nueva Firma es entrada;
            else (SI)
                if (Última firma es **'entrada'**) then (SI)
                    :Nueva Firma es **'salida'**;
                else (NO)
                    :Nueva Firma es **'entrada'**;
                endif
                :Obtener ID de Última Firma **del sistema**;
                :ID de Nueva Firma = ID de Última Firma+1;
                :Registrar Nueva Firma;
                :Vincular Nueva Firma a CI de funcionario;
            endif
        else (NO)
            :ERROR: CI no registrada;
        endif
        :Mostrar Resultado\n(Nueva Firma o Error);
    stop

@enduml